# ndArray : Creation and Properties

In [42]:
import numpy as np
 #1d array
array1  = np.array([1,2,3,4])#dtype :int64
a2 = np.array(['a','b',2,4]) # dtype: U21
a3 =np.array(["fjir","bjd"]) #U4
a4 = np.array(['a','b','c']) #u1
a5 =np.array([1.2,2.4,6.7]) #float64
a6 =np.array([1,2.4,6.7]) #float64
a7 =np.array([1, 2 ,6.7]) #float64

In [43]:
#dtype
print(array1.dtype)
print(a2.dtype)
print(a3.dtype)
print(a4.dtype)
print(a5.dtype)
print(a6.dtype)
print(a7.dtype)

int64
<U21
<U4
<U1
float64
float64
float64


In [44]:
#dimensions of the array can be obtained by using ndim
print(array1.ndim)

#shape:(= length of each dimension) of the NumPy array as a tuple
print(array1.shape)
#size: (= total number of elements) of the NumPy array
print(array1.size)
#dtype: gives datatype of the array
#len() returns the size of the first dimension. Equivalent to shape[0]
print(len(array1))
print(array1.shape[0])

1
(4,)
4
4
4


In [45]:
# 2D Array
twoD = np.array([[2,3],[4,5]])
twoD

array([[2, 3],
       [4, 5]])

In [46]:
print(twoD.ndim)
print(twoD.shape)
print(twoD.size)
print(twoD.dtype)
print(len(twoD))
print(twoD.shape[0])


2
(2, 2)
4
int64
2
2


In [47]:
#3d array
d3 = np.array([[[2,3,5],[4,5,6]],[[2,3,5],[4,5,6]]])
d3

array([[[2, 3, 5],
        [4, 5, 6]],

       [[2, 3, 5],
        [4, 5, 6]]])

In [48]:
print(d3.ndim)
print(d3.shape)
print(d3.size)
print(d3.dtype)
print(len(d3))
print(d3.shape[0])

3
(2, 2, 3)
12
int64
2
2


In [49]:
t3 = np.array([(1,'a',3.0),(2,'b',3.5)]) 
t3

array([['1', 'a', '3.0'],
       ['2', 'b', '3.5']], dtype='<U32')

In [50]:
print(t3.ndim)
print(t3.shape)
print(t3.size)
print(t3.dtype)
print(len(t3))
print(t3.shape[0])

2
(2, 3)
6
<U32
2
2


# Random Array creation methods
* uniform
* normal
* range with step
* equally seperated
* reshape to another form
* linespace 
* logspace

In [51]:
#random numbers from a uniform distribution between [0,1]
print(np.random.rand(5))
#normal distribution
print(np.random.randn(5))
#integer btwn -10 and 10 with size 2
print(np.arange(-10,10,2))
#2-dimensional array of integers from 0 to 11'
print(np.arange(12).reshape(3,4)) # reshape to a matrix
# split interval [0,1] into 10 equally separated values
print(np.linspace(0,1,10))
 # create ndarray with values from 10^-3 to 10^3
print(np.logspace(-3,3,7)) 


[0.97659021 0.83463433 0.59132204 0.54054091 0.76936867]
[ 0.96176407  1.70759998 -0.25945682 -1.30173686  0.60093783]
[-10  -8  -6  -4  -2   0   2   4   6   8]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
[1.e-03 1.e-02 1.e-01 1.e+00 1.e+01 1.e+02 1.e+03]


# MATRIX: zeros, ones, identity

In [52]:
print('A 2 x 3 matrix of zeros')
print(np.zeros((2,3)))        # a matrix of zeros

print('\nA 3 x 2 matrix of ones')
print(np.ones((3,2)))         # a matrix of ones

print('\nA 3 x 3 identity matrix')
print(np.eye(3))              # a 3 x 3 identity matrix

A 2 x 3 matrix of zeros
[[0. 0. 0.]
 [0. 0. 0.]]

A 3 x 2 matrix of ones
[[1. 1.]
 [1. 1.]
 [1. 1.]]

A 3 x 3 identity matrix
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#Elementwise Operations

In [53]:
# single element operations
x = np.array([1,2,3,4,6])
print(x+1)
print(x-6)
print(x*9)
print(x/2)
print(x % 1)
print(x//2)

[2 3 4 5 7]
[-5 -4 -3 -2  0]
[ 9 18 27 36 54]
[0.5 1.  1.5 2.  3. ]
[0 0 0 0 0]
[0 1 1 2 3]


In [54]:
# operations between 2 arrays
y = np.random.rand(5)
print(x+y)
print(x-y)
print(x*y)
print(x/y)
print(x//y)
print(x%y)

[1.01151063 2.49970651 3.4957046  4.50446955 6.24935174]
[0.98848937 1.50029349 2.5042954  3.49553045 5.75064826]
[0.01151063 0.99941302 1.48711381 2.01787819 1.49611042]
[86.87620462  4.00234932  6.05199142  7.92912082 24.06239503]
[86.  4.  6.  7. 24.]
[0.01008567 0.00117397 0.02577239 0.46871316 0.01555831]


# Indexing and Slicing

In [55]:
#Indexing and Slicing
p = np.arange(-5,5)
q =  p[1:4] #slicing
print(p)
print(q) 
q[:] = 1000 # call by refrence happens
print(p)
print(q)

z = p[1:4].copy()
print(z)
z[:] = 500 # here call by value action takes place(after using copy())
print(z)
print(p)

[-5 -4 -3 -2 -1  0  1  2  3  4]
[-4 -3 -2]
[  -5 1000 1000 1000   -1    0    1    2    3    4]
[1000 1000 1000]
[1000 1000 1000]
[500 500 500]
[  -5 1000 1000 1000   -1    0    1    2    3    4]


# Access elements of nd array

In [56]:
d2 = np.array([[2,3],[4,5],[5,7]])
d2

array([[2, 3],
       [4, 5],
       [5, 7]])

In [57]:
d2[2] # gives 3rd row

array([5, 7])

In [58]:
d2[:][2] # 3rd row

array([5, 7])

In [59]:
d2[:,1] # acess column value

array([3, 5, 7])

In [60]:
d2[1:,] # rows 1 and 2 not 0

array([[4, 5],
       [5, 7]])

In [61]:
d2[1,:] # only row 1

array([4, 5])

In [62]:
d2[:2,:1] # 0,1 ROW and 0 column

array([[2],
       [4]])

# Linear Algebra

In [63]:
# Genrate random matrix
x = np.random.randn(3) #vector of order 1*3
y = np.random.rand(3,3) # 3*3 
print(x)
print(y)

[-1.77291871 -0.59452823 -0.04610787]
[[3.20524305e-04 2.44293566e-01 1.92455553e-01]
 [9.43634052e-01 3.19730303e-01 2.32871537e-02]
 [3.18293392e-01 7.24404333e-02 5.32524623e-01]]


In [64]:
# Transpose of a matrix
print(x.T) # not transposed : handled automatically during calculations
print(y.T) # transposed

[-1.77291871 -0.59452823 -0.04610787]
[[3.20524305e-04 9.43634052e-01 3.18293392e-01]
 [2.44293566e-01 3.19730303e-01 7.24404333e-02]
 [1.92455553e-01 2.32871537e-02 5.32524623e-01]]


In [67]:
# matrix-vector multiplication
print(y.dot(x))
print(x.dot(y))

[-0.1546814  -1.86414888 -0.63192977]
[-0.57626118 -0.6265414  -0.3796065 ]


In [68]:
#matrix-matrix product/square
x.T.dot(x)


3.4988305207445998

In [72]:
#Inverse
print(np.linalg.inv(y))
#determinant
print(np.linalg.det(y))
#Eigen value and vector
s,u = np.linalg.eig(y)
print(s)
print(u)

[[-1.32399362  0.91223943  0.43860219]
 [ 3.88844839  0.4797699  -1.42627388]
 [ 0.26240577 -0.61051547  1.8097111 ]]
-0.12732487886953528
[-0.37584681  0.81039291  0.41802935]
[[ 0.58952122 -0.3582913  -0.09100586]
 [-0.79496324 -0.717415   -0.7076248 ]
 [-0.14317186 -0.59744712  0.70070327]]
